# Generated by Django 4.1.3 on 2022-12-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
