# Generated by Django 4.1.3 on 2022-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=30)),
            ],
        ),
    ]
