# Generated by Django 4.1.3 on 2022-12-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
