# Generated by Django 4.1.3 on 2022-12-24 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploaded img/')),
                ('username', models.CharField(max_length=20)),
                ('caption', models.TextField(max_length=40)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
