# Generated by Django 4.1.3 on 2022-12-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='uploaded_img/'),
        ),
    ]
