# Generated by Django 4.1.3 on 2022-12-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_profiles_bio_profiles_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='password',
        ),
    ]
