# Generated by Django 4.1.3 on 2022-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_post_video_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
