# Generated by Django 4.1.3 on 2022-12-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_remove_post_video_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='username',
            new_name='user',
        ),
    ]
