# Generated by Django 4.1.3 on 2023-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
